---
- hosts: qa
  become: true
  tasks:
    - yum: 
        name:
          - httpd
        state: present
    - service: name=httpd state=started enabled=yes
    - raw: "echo Welcome to ubalepriya | sudo tee /var/www/html/index.html"
    